// Generated by tools/build_assets.py - do not edit by hand.
// Plain numbers only: this file is included from assembly as well as C++.
#ifndef STA_CONSTS_H
#define STA_CONSTS_H
#define COLS 64
#define ROWS 56
#define COLBYTES 7
#define HORIZON 19
#define CAM_H 150
#define CAM_BACK 397
#define MAXD 10240
#define MAXD_CELLS 40
#define SPRITE_MAXD 6144
#define N_SIZES 24
#define CELL_EDGE 255
#define NAV_C0 26
#define NAV_ARROW_COLS 6
#define NAV_BOX_C0 33
#define NAV_BOX_COLS 9
#define NAV_ARROW_BYTES 48
#define TILE_PLAIN_ROAD 17
#endif
