// Generated by tools/build_assets.py - do not edit by hand.
#pragma once
#include <stdint.h>

// development places: the data sits at the end of the 16 MB chip, in front
// of the 4 KB the game may write to (the way the ArduboyFX tools have it)
#define FX_DATA_PAGE 0xEED6
#define FX_SAVE_PAGE 0xFFF0
#define FX_DATA_BYTES 1120768UL

#define FX_HEADER 0x000000UL
#define FX_MAP 0x000010UL
#define FX_PROP_TABLE 0x010010UL
#define FX_PROP_DATA 0x010410UL
#define FX_SPRITE_INDEX 0x011850UL
#define FX_SPRITE_DATA 0x025490UL
#define FX_TITLE 0x10F030UL
#define FX_MAP_PICTURE 0x10F3B0UL
#define FX_ARROWS 0x10FBB0UL
#define FX_JOBS 0x1101B0UL

#define SPR_HERO_SEDAN_L 0
#define SPR_HERO_SEDAN_M 1
#define SPR_HERO_SEDAN_D 2
#define SPR_HERO_TAXI 3
#define SPR_HERO_VAN 4
#define SPR_HERO_SPORTS 5
#define SPR_HERO_POLICE 6
#define SPR_STAND 7
#define SPR_WALK0 8
#define SPR_WALK1 9
#define SPR_WALK2 10
#define SPR_WALK3 11
#define SPR_AIM 12
#define SPR_FIRE 13
#define SPR_AIM_LEFT 14
#define SPR_FIRE_LEFT 15
#define SPR_SEDAN_L 16
#define SPR_SEDAN_M 17
#define SPR_SEDAN_D 18
#define SPR_TAXI 19
#define SPR_VAN 20
#define SPR_SPORTS 21
#define SPR_POLICE 22
#define SPR_POLICE_B 23
#define SPR_PED_A0 24
#define SPR_PED_A1 25
#define SPR_PED_A2 26
#define SPR_PED_A3 27
#define SPR_PED_B0 28
#define SPR_PED_B1 29
#define SPR_PED_B2 30
#define SPR_PED_B3 31
#define SPR_PED_C0 32
#define SPR_PED_C1 33
#define SPR_PED_C2 34
#define SPR_PED_C3 35
#define SPR_COP0 36
#define SPR_COP1 37
#define SPR_COP2 38
#define SPR_COP3 39
#define SPR_PED_A_DOWN 40
#define SPR_PED_B_DOWN 41
#define SPR_PED_C_DOWN 42
#define SPR_COP_DOWN 43
#define SPR_COP_AIM 44
#define SPR_COP_FIRE 45
#define SPR_WASTED 46
#define SPR_BUSTED 47
#define SPR_PASSED 48
#define SPR_FAILED 49
#define SPR_TREE 50
#define SPR_LAMP 51
#define SPR_PHONE 52
#define SPR_MARK 53
#define SPR_MARK_UP 54
#define SPR_SPARK 55
#define SPR_TRACER 56
#define SPR_CASH 57
#define SPR_CASH_UP 58
// groups: first set of each; the members follow in order
#define SPR_HERO_CAR SPR_HERO_SEDAN_L   // + car kind
#define SPR_HERO_STAND SPR_STAND     // standing still; + 1 + step of the walk, 0..3
#define SPR_HERO_AIM SPR_AIM         // pistol up; + 1 with the flash, + 2 in the left hand
#define SPR_CAR SPR_SEDAN_L         // + car kind
#define SPR_PED SPR_PED_A0           // + 4 * kind + step
#define SPR_PED_DOWN SPR_PED_A_DOWN  // + kind
#define N_CAR_KINDS 7
#define N_PED_KINDS 4
#define CAR_SEDAN_L 0
#define CAR_SEDAN_M 1
#define CAR_SEDAN_D 2
#define CAR_TAXI 3
#define CAR_VAN 4
#define CAR_SPORTS 5
#define CAR_POLICE 6
// sprite sets: angles, sizes, first index entry (16 bit)
const uint8_t SPRITE_SETS[236] PROGMEM = {64, 1, 0, 0, 64, 1, 64, 0, 64, 1, 128, 0, 64, 1, 192, 0, 64, 1, 0, 1, 64, 1, 64, 1, 64, 1, 128, 1, 32, 1, 192, 1, 32, 1, 224, 1, 32, 1, 0, 2, 32, 1, 32, 2, 32, 1, 64, 2, 32, 1, 96, 2, 32, 1, 128, 2, 32, 1, 160, 2, 32, 1, 192, 2, 32, 24, 224, 2, 32, 24, 224, 5, 32, 24, 224, 8, 32, 24, 224, 11, 32, 24, 224, 14, 32, 24, 224, 17, 32, 24, 224, 20, 32, 24, 224, 23, 8, 24, 224, 26, 8, 24, 160, 27, 8, 24, 96, 28, 8, 24, 32, 29, 8, 24, 224, 29, 8, 24, 160, 30, 8, 24, 96, 31, 8, 24, 32, 32, 8, 24, 224, 32, 8, 24, 160, 33, 8, 24, 96, 34, 8, 24, 32, 35, 8, 24, 224, 35, 8, 24, 160, 36, 8, 24, 96, 37, 8, 24, 32, 38, 8, 24, 224, 38, 8, 24, 160, 39, 8, 24, 96, 40, 8, 24, 32, 41, 8, 24, 224, 41, 8, 24, 160, 42, 1, 1, 96, 43, 1, 1, 97, 43, 1, 1, 98, 43, 1, 1, 99, 43, 1, 24, 100, 43, 4, 24, 124, 43, 8, 24, 220, 43, 1, 24, 156, 44, 1, 24, 180, 44, 1, 24, 204, 44, 1, 24, 228, 44, 1, 24, 252, 44, 1, 24, 20, 45};
#define PROP_TREE 0
#define PROP_LAMP 1
#define PROP_PHONE 2
// missions (tools/missions.py): so many, 512 bytes each on the flash chip
#define N_JOBS 12
#define JOB_TEXT 16        // 6 lines of 30 signs, as places in the lettering
#define JOB_LINES 6
#define JOB_LINE 30
#define JOB_STEPS 224      // steps of 32 bytes: what is asked for, then two hints of 12 signs
#define JOB_HINT 12
#define JOB_PAY_UNIT 50
#define STEP_END 0
#define STEP_GO 1
#define STEP_KILL 2
#define STEP_LOSE 3
#define STEP_COUNT 0x08
#define STEP_CAR 0x10
#define STEP_STOP 0x20
#define STEP_MARK 0x40
#define STEP_COPS 0x80
#define STEP_ANY_CAR 7
// the telephones that offer them. The first mission of every one (they are its
// own up to the first one of the next)
const uint8_t JOB_FIRST[4] PROGMEM = {0, 4, 8, 12};
// the first letter of whoever is on the line (its
// place in the lettering), for the map
const uint8_t PHONE_SIGNS[3] PROGMEM = {33, 23, 14};
// and where they stand (8.8 cells)
#define N_PHONES 3
const uint16_t PHONES[6] PROGMEM = {0x5BA0, 0x9AE0, 0x77A0, 0x63E0, 0xD1A0, 0xCDE0};
#define PROP_CHUNK_MAX 24
